# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d28d5ac93b920787fdd1cc105784e982f9e88cf3d32468237b2caf4022bd85c4048ab283e9184b7a1838fd90c8a95174dc9936b8714991a924abbda0edf44c7

test:
  secret_key_base: 7bf7c379f12193a7d717274d0ec24fb08de91c973427c1f781fd0ae39af7483d1d19eeca4c521dfadfb4282d902bbf092a254a4d5f8e58e47bbbe345ffecca94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
